---
title: "United States"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, fig.width = 8, fig.height = 6, fig.retina = 2)

library(tidyverse)
library(lubridate)
library(ggrepel)
library(paletteer)
library(prismatic)
library(here)

load(here("data", "covid_data.Rdata"))

updated_at <- now()
```

**Updated at:** `r updated_at`

# U.S. Totals

## Cases

```{r us_total_cases}
nyt_us_total %>% 
  filter(date >= start_date) %>% 
  ggplot(aes(x = date, y = cases)) +
  geom_line(size = 1) +
  scale_y_continuous(labels = scales::comma) +
  theme_covid +
  labs(title = str_glue("Cumulative Cases of Coronavirus in the U.S."),
       x = NULL,
       y = "Cumulative Cases")
```


```{r us_weekly_change}
nyt_us_total %>% 
  filter(date >= start_date) %>% 
  ggplot(aes(x = date, y = daily_new_cases_raw)) +
  geom_col(fill = ghColorSelect("blue")) +
  geom_line(aes(y = daily_new_cases), size = 1, linetype = "dashed") +
  scale_y_continuous(labels = scales::comma) +
  theme_covid +
  labs(title = str_glue("Daily New Cases of Coronavirus"),
       x = NULL,
       y = "New Cases")
```


## Deaths

```{r us_total_deaths}
nyt_us_total %>% 
  filter(date >= start_date) %>% 
  ggplot(aes(x = date, y = deaths)) +
  geom_line(size = 1) +
  scale_y_continuous(labels = scales::comma) +
  theme_covid +
  labs(title = str_glue("Cumulative Deaths of Coronavirus in the U.S."),
       x = NULL,
       y = "Cumulative Deaths")
```


```{r us_weekly_change_deaths}
nyt_us_total %>% 
  filter(date >= start_date) %>% 
  ggplot(aes(x = date, y = daily_deaths_raw)) +
  geom_col(fill = ghColorSelect("purple")) +
  geom_line(aes(y = daily_deaths), size = 1, linetype = "dashed") +
  scale_y_continuous(labels = scales::comma) +
  theme_covid +
  labs(title = str_glue("Daily COVID Deaths"),
       x = NULL,
       y = "New Deaths")
```

# Stats by State


## Cases

```{r state_raw_cases}
gpdf <- nyt_state_df %>% 
  group_by(state) %>% 
  mutate(core = if_else(
           state %nin% top_n_state(nyt_state_df, n=7, wt = cases), "", 
           state 
           ),
         linesize = if_else(core == "", 0.5, 1),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup()

gpdf %>% 
  filter(date >= start_date) %>% 
  ggplot(aes(x = date, y = cases, group = state, label = end_label, color = core)) +
  geom_line(aes(size = linesize, alpha = linesize)) +
  geom_text_repel(segment.color = NA, nudge_x = 2, nudge_y = 0.1) +
  scale_y_continuous(labels = scales::comma) +
  theme_covid +
  labs(title = str_glue("Cumulative Cases of Coronavirus by State"),
       x = NULL,
       y = "Cumulative Cases")
```

```{r state_per_capita}
gpdf <- nyt_state_df %>% 
  group_by(state) %>% 
  mutate(core = if_else(
           state %nin% top_n_state(nyt_state_df, n=7, wt = cases_per_capita), "", 
           state 
           ),
         linesize = if_else(core == "", 0.5, 1),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup()
gpdf %>% 
  ggplot(aes(x = date, y = cases_per_capita, group = state, label = end_label, color = core)) +
  geom_line(aes(size = linesize, alpha = linesize)) +
  geom_text_repel(segment.color = NA, nudge_x = 2) +
  scale_y_continuous(labels = scales::comma) +
  theme_covid +
  labs(title = str_glue("Cases per Capita of Coronavirus by State"),
       x = NULL,
       y = "Cases Per 1,000 Population")
```





```{r state_weekly_change}
gpdf <- nyt_state_df %>% 
  group_by(state) %>% 
  mutate(core = if_else(
           state %nin% top_n_state(nyt_state_df, n=7, wt = daily_new_cases), "", 
           state 
           ),
         linesize = if_else(core == "", 0.5, 1),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup()
gpdf %>% 
  ggplot(aes(x = date, y = daily_new_cases, group = state, label = end_label, color = core)) +
  geom_line(aes(size = linesize, alpha = linesize)) +
  geom_text_repel(segment.color = NA, nudge_x = 2) +
  scale_y_continuous(labels = scales::comma) +
  theme_covid +
  labs(title = str_glue("Avg. Daily New Cases of Coronavirus By State"),
       caption = "Based on a 7 day moving average",
       x = NULL,
       y = "New Cases")
```

```{r state_weekly_change_raw}
gpdf %>% 
  filter(state %in% top_n_state(nyt_state_df, n=7, wt = daily_new_cases)) %>% 
  ggplot(aes(x = date, y = daily_new_cases_raw, fill = state)) +
  geom_col() +
  scale_y_continuous(labels = scales::comma) +
  scale_x_date(limits = c(start_date, NA)) +
  theme(
    panel.background = element_blank(),
    panel.grid.major.y = element_line(color = ghColorSelect("grey-200"))
  ) +
  scale_fill_manual(values = ghColorSelect("grey-400", "blue", "red", "green", "yellow-800", "purple", "orange", "pink")) +
  guides(fill = FALSE) +
  facet_grid(rows = "state", scales = "free_y") +
  labs(title = str_glue("Avg. Daily New Cases of Coronavirus By State"),
       caption = "Based on a 7 day moving average",
       x = NULL,
       y = "New Cases")
```

```{r state_change_per_capita}
gpdf <- nyt_state_df %>% 
  group_by(state) %>% 
  mutate(core = if_else(
           state %nin% top_n_state(nyt_state_df, n=7, wt = daily_new_per_capita), "", 
           state 
           ),
         linesize = if_else(core == "", 0.5, 1),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup()
gpdf %>% 
  ggplot(aes(x = date, y = daily_new_per_capita*10000, group = state, label = end_label, color = core)) +
  geom_line(aes(size = linesize, alpha = linesize)) +
  geom_text_repel(segment.color = NA, nudge_x = 2) +
  scale_y_continuous(labels = scales::comma) +
  theme_covid +
  labs(title = str_glue("Daily New Cases Per Capita of Coronavirus by State"),
       x = NULL,
       y = "New Cases per 10,000 Population")
```

## Deaths


```{r deaths_raw_cases}
gpdf <- nyt_state_df %>% 
  group_by(state) %>% 
  mutate(core = if_else(
           state %nin% top_n_state(nyt_state_df, n=7, wt = deaths), "", 
           state 
           ),
         linesize = if_else(core == "", 0.5, 1),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup()

gpdf %>% 
  filter(date >= start_date) %>% 
  ggplot(aes(x = date, y = deaths, group = state, label = end_label, color = core)) +
  geom_line(aes(size = linesize, alpha = linesize)) +
  geom_text_repel(segment.color = NA, nudge_x = 2, nudge_y = 0.1) +
  scale_y_continuous(labels = scales::comma) +
  theme_covid +
  labs(title = str_glue("Cumulative COVID-19 Deaths by State"),
       x = NULL,
       y = "Cumulative Deaths")
```

```{r deaths_per_capita}
gpdf <- nyt_state_df %>% 
  group_by(state) %>% 
  mutate(core = if_else(
           state %nin% top_n_state(nyt_state_df, n=7, wt = deaths_per_capita), "", 
           state 
           ),
         linesize = if_else(core == "", 0.5, 1),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup()
gpdf %>% 
  ggplot(aes(x = date, y = deaths_per_capita, group = state, label = end_label, color = core)) +
  geom_line(aes(size = linesize, alpha = linesize)) +
  geom_text_repel(segment.color = NA, nudge_x = 2) +
  scale_y_continuous(labels = scales::comma) +
  theme_covid +
  labs(title = str_glue("COVID-19 Deaths per Capita by State"),
       x = NULL,
       y = "Deaths Per 1,000 Population")
```





```{r deaths_weekly_change}
gpdf <- nyt_state_df %>% 
  group_by(state) %>% 
  mutate(core = if_else(
           state %nin% top_n_state(nyt_state_df, n=7, wt = daily_deaths), "", 
           state 
           ),
         linesize = if_else(core == "", 0.5, 1),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup()
gpdf %>% 
  ggplot(aes(x = date, y = daily_deaths, group = state, label = end_label, color = core)) +
  geom_line(aes(size = linesize, alpha = linesize)) +
  geom_text_repel(segment.color = NA, nudge_x = 2) +
  scale_y_continuous(labels = scales::comma) +
  theme_covid +
  labs(title = str_glue("Avg. Daily New COVID Deaths By State"),
       caption = "Based on 7 day moving average",
       x = NULL,
       y = "New Deaths in Last 7 Days")
```


```{r deaths_change_per_capita}
gpdf <- nyt_state_df %>% 
  group_by(state) %>% 
  mutate(core = if_else(
           state %nin% top_n_state(nyt_state_df, n=7, wt = daily_deaths_per_capita), "", 
           state 
           ),
         linesize = if_else(core == "", 0.5, 1),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup()
gpdf %>% 
  ggplot(aes(x = date, y = daily_deaths_per_capita, group = state, label = end_label, color = core)) +
  geom_line(aes(size = linesize, alpha = linesize)) +
  geom_text_repel(segment.color = NA, nudge_x = 2) +
  scale_y_continuous(labels = scales::comma) +
  theme_covid +
  labs(title = str_glue("Avg. Daily New COVID Deaths Per Capita by State"),
       caption = "Based on 7 day moving average",
       x = NULL,
       y = "New Deaths in Last 7 Days per 1,000 Population")
```