---
title: "COVID-19 Data"
output: github_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# get latest data
remotes::install_github("kjhealy/covdata")

library(tidyverse)
library(covdata)
library(ggrepel)
library(paletteer)
library(prismatic)

## Convenince "Not in" operator
"%nin%" <- function(x, y) {
  return( !(x %in% y) )
}

ca_county_pops <- read_csv("ca_county_pops.csv") %>% 
  mutate(county = str_replace(County, " County", ""))
il_county_pops <- read_csv("il_county_pops.csv") %>% 
  mutate(county = str_replace(County, " County", ""))

source("add_county_pop.R")

top_n_counties <- function(data, n = 5, wt = cases, label = full_name) {
  data %>%
  group_by(full_name) %>%
  filter(date == max(date)) %>%
  ungroup() %>%
  top_n(n, wt = {{ wt }}) %>%
  pull({{ label }})
}

top_n_state <- function(data, n = 5, wt = cases) {
  data %>%
  group_by(state) %>%
  filter(date == max(date)) %>%
  ungroup() %>%
  top_n(n, wt = {{ wt }}) %>%
  pull(state)
}

theme_covid <-   list(theme(
    panel.background = element_blank(),
    panel.grid.major.y = element_line(color = ghColorSelect("grey-200"))
  ),
  scale_color_manual(values = ghColorSelect("grey-400", "blue", "red", "green", "yellow-800", "purple", "orange", "pink")),
  scale_size_identity(),
  guides(color = FALSE) )

kable <- partial(knitr::kable, format.args = list(big.mark = ","))
```

# California

## Total Cases

```{r}
county_df <- nyt_county_data %>% 
  filter(state == "California") %>% 
  group_by(county) %>% 
  arrange(date) %>% 
  mutate(percent_weekly_change = (cases - lag(cases)) / lag(cases),
         percent_weekly_change = case_when(
           cases < 100 ~ NA_real_,
           percent_weekly_change == Inf ~ NA_real_,
           date == max(date) ~ percent_weekly_change,
           TRUE ~ NA_real_
         )) %>% 
  ungroup()
gpdf <- county_df %>% 
  filter(full_name %in% top_n_counties(county_df, n = 20, wt = cases))
gpdf <- gpdf %>% 
  group_by(county) %>% 
  mutate(days_since = date - min(date),
         core = if_else(
           county %nin% top_n_counties(gpdf, n=7, wt = cases, label = county), "", 
           county 
           ),
         linesize = if_else(core == "", 0.5, 1),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup()


gpdf %>% 
  ggplot(aes(x = days_since, y = cases, group = county, label = end_label, color = core)) +
  geom_line(size = 1) +
  geom_text_repel(segment.color = NA, nudge_x = 2, nudge_y = 0.1) +
  scale_y_continuous(labels = scales::comma) +
  #scale_y_log10() +
  #scale_x_continuous(limits = c(0,100)) +
  scale_color_manual(values = ghColorSelect("grey-400", "blue", "red", "green", "yellow-800", "purple", "orange", "pink")) +
  guides(color = FALSE) +
  labs(title = "Cumulative Cases of Coronavirus in California Counties",
       x = "Days Since First Case",
       y = "Cumulative Cases")
ggsave("img/ca_counties.png", width = 8, height = 6, dpi = 300)
```

## Cases Per Capita

```{r}
start_date <- ymd("2020-04-01")
end_date <- today() + days(10)
gpdf %>% 
  filter(date >= ymd("2020-04-01")) %>% 
    ggplot(aes(x = date, y = cases_per_capita*1000, group = full_name, label = end_label, color = core)) +
  geom_line(aes(size = linesize)) +
  geom_text_repel(segment.color = NA, nudge_x = 2) +
  #scale_y_log10() +
  #scale_x_continuous(limits = c(0,100)) +
  scale_color_manual(values = ghColorSelect("grey-400", "blue", "red", "green", "yellow-800", "purple", "orange", "pink")) +
  scale_size_identity() +
  scale_x_date(limits = c(start_date, end_date)) +
  guides(color = FALSE) +
  labs(title = "Cases Per Capita of Coronavirus in CA Counties",
       x = "Days Since First Case",
       y = "Cases Per 1,000 Population")
ggsave("img/ca_counties_per_capita_calendar.png", width = 8, height = 6, dpi = 400)
```

## Rural Counties

```{r}
county_df <- nyt_county_data %>% 
  filter(state == "California" & population < 1000000 & county != "San Francisco")
gpdf <- county_df %>% 
  filter(full_name %in% top_n_counties(county_df, n = 20, wt = cases_per_capita))
gpdf <- gpdf %>% 
  group_by(county) %>% 
  mutate(days_since = date - min(date),
         core = if_else(
           county %nin% top_n_counties(gpdf, n=7, wt = cases_per_capita, label = county), "", 
           county 
           ),
         linesize = if_else(core == "", 0.5, 1),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup()


gpdf %>% 
    ggplot(aes(x = days_since, y = cases_per_capita*1000, group = full_name, label = end_label, color = core)) +
  geom_line(aes(size = linesize)) +
  geom_text_repel(segment.color = NA, nudge_x = 2) +
  #scale_y_log10() +
  #scale_x_continuous(limits = c(0,100)) +
  scale_color_manual(values = ghColorSelect("grey-400", "blue", "red", "green", "yellow-800", "purple", "orange", "pink")) +
  scale_size_identity() +
  guides(color = FALSE) +
  labs(title = "Cases Per Capita of Coronavirus in non-Urban CA Counties",
       caption = "Counties with less than 1 million population, excluding San Francisco",
       x = "Days Since First Case",
       y = "Cases Per 1,000 Population")
ggsave("img/ca_counties_per_capita.png", width = 8, height = 6, dpi = 400)
```



## CA Cases in Last 7 Days

```{r}
county_df <- nyt_county_data %>% 
  filter(state == "California")
gpdf <- county_df %>% 
  filter(full_name %in% top_n_counties(county_df, n = 20, wt = weekly_change))
gpdf <- gpdf %>% 
  group_by(county) %>% 
  mutate(days_since = date - min(date),
         core = if_else(
           county %nin% top_n_counties(gpdf, n=7, wt = weekly_change, label = county), "", 
           county 
           ),
         linesize = if_else(core == "", 0.5, 1),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup()
start_date <- ymd("2020-04-01")
end_date <- today() + days(10)

gpdf %>% 
  filter(date >= start_date) %>% 
    ggplot(aes(x = date, y = weekly_change, group = full_name, label = end_label, color = core)) +
  geom_line(aes(size = linesize)) +
  geom_text_repel(segment.color = NA, nudge_x = 2) +
  #scale_y_log10() +
  #scale_x_continuous(limits = c(0,100)) +
  scale_color_manual(values = ghColorSelect("grey-400", "blue", "red", "green", "yellow-800", "purple", "orange", "pink")) +
  scale_size_identity() +
  scale_x_date(limits = c(start_date, end_date)) +
  guides(color = FALSE) +
  labs(title = "Weekly New Cases of Coronavirus in CA Counties",
       x = "Days Since First Case",
       y = "New Cases in Last 7 Days")
ggsave("img/ca_counties_weekly_change.png", width = 8, height = 6, dpi = 400)
```

```{r}
start_date <- ymd("2020-04-01")
end_date <- today() + days(10)
nyt_county_data %>% 
  filter(date >= start_date & state == "California" & county %in% bay_area) %>% 
  group_by(county) %>% 
  mutate(days_since = date - min(date),
         core = if_else(
           county %nin% bay_area, "", 
           county 
           ),
         linesize = if_else(core == "", 0.5, 1),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup() %>% 
    ggplot(aes(x = date, y = cases, group = full_name, label = end_label, color = core)) +
  geom_line(aes(size = linesize)) +
  geom_text_repel(segment.color = NA, nudge_x = 2) +
  #scale_y_log10() +
  #scale_x_continuous(limits = c(0,100)) +
  scale_color_manual(values = ghColorSelect("grey-400", "blue", "red", "green", "yellow-800", "purple", "orange", "pink", "blue-400")) +
  scale_size_identity() +
  scale_x_date(limits = c(start_date, end_date)) +
  guides(color = FALSE) +
  labs(title = "Cases Per Capita of Coronavirus in CA Counties",
       x = "Days Since First Case",
       y = "New Cases in Last 7 Days")
ggsave("img/bay_area_cases.png", width = 8, height = 6, dpi = 400)
```




```{r}
county_df <- nyt_county_data %>% 
  filter(state == "California")
gpdf <- county_df %>% 
  filter(county %in% bay_area)
gpdf <- gpdf %>% 
  group_by(county) %>% 
  mutate(days_since = date - min(date),
         core = if_else(
           county %nin% bay_area, "", 
           county 
           ),
         linesize = if_else(core == "", 0.5, 1),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup()
start_date <- ymd("2020-04-01")
end_date <- today() + days(10)

gpdf %>% 
  filter(date >= start_date) %>% 
    ggplot(aes(x = date, y = weekly_change, group = full_name, label = end_label, color = core)) +
  geom_line(aes(size = linesize)) +
  geom_text_repel(segment.color = NA, nudge_x = 2) +
  #scale_y_log10() +
  #scale_x_continuous(limits = c(0,100)) +
  scale_color_manual(values = ghColorSelect("grey-400", "blue", "red", "green", "yellow-800", "purple", "orange", "pink", "blue-400")) +
  scale_size_identity() +
  scale_x_date(limits = c(start_date, end_date)) +
  guides(color = FALSE) +
  labs(title = "Weekly New Cases of Coronavirus in CA Counties",
       x = "Days Since First Case",
       y = "New Cases in Last 7 Days")
ggsave("img/bay_area_weekly_change.png", width = 8, height = 6, dpi = 400)
```


```{r}
county_df <- nyt_county_data %>% 
  filter(state == "California")
gpdf <- county_df %>% 
  filter(full_name %in% top_n_counties(county_df, n = 20, wt = change_per_capita))
gpdf <- gpdf %>% 
  group_by(county) %>% 
  mutate(days_since = date - min(date),
         core = if_else(
           county %nin% top_n_counties(gpdf, n=7, wt = change_per_capita, label = county), "", 
           county 
           ),
         linesize = if_else(core == "", 0.5, 1),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup() %>% 
  filter(!is.na(weekly_change))

gpdf %>% 
  #filter(date >= ymd("2020-04-01")) %>% 
    ggplot(aes(x = days_since, y = change_per_capita*1000, group = full_name, label = end_label, color = core)) +
  geom_line(aes(size = linesize)) +
  geom_text_repel(segment.color = NA, nudge_x = 2) +
  #scale_y_log10() +
  #scale_x_continuous(limits = c(0,100)) +
  scale_color_manual(values = ghColorSelect("grey-400", "blue", "red", "green", "yellow-800", "purple", "orange", "pink")) +
  scale_size_identity() +
  guides(color = FALSE) +
  labs(title = "New Cases In Last 7 Days Per Capita, California Counties",
       x = "Days Since First Case",
       y = "New Cases in Last 7 Days Per 1,000 Pop.")
ggsave("img/ca_weekly_counties.png", width = 8, height = 6, dpi = 400)
```



```{r ca_percent_weekly}
county_df <- nyt_county_data %>% 
  filter(state == "California")
gpdf <- county_df %>% 
  filter(full_name %in% top_n_counties(county_df, n = 20, wt = percent_weekly_change))
gpdf <- gpdf %>% 
  group_by(county) %>% 
  mutate(days_since = date - min(date),
         core = if_else(
           county %nin% top_n_counties(gpdf, n=7, wt = percent_weekly_change, label = county), "", 
           county 
           ),
         linesize = if_else(core == "", 0.5, 1),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup() %>% 
  filter(!is.na(weekly_change))

gpdf %>% 
  filter(date >= ymd("2020-04-01")) %>% 
    ggplot(aes(x = date, y = percent_weekly_change, group = full_name, label = end_label, color = core)) +
  geom_line(aes(size = linesize)) +
  geom_text_repel(segment.color = NA, nudge_x = 2) +
  #scale_y_log10() +
  #scale_x_continuous(limits = c(0,100)) +
  scale_color_manual(values = ghColorSelect("grey-400", "blue", "red", "green", "yellow-800", "purple", "orange", "pink")) +
  scale_size_identity() +
  scale_x_date(limits = c(start_date, end_date)) +
  scale_y_continuous(labels = scales::percent) +
  guides(color = FALSE) +
  labs(title = "Percent Change in Weekly New Cases, California Counties",
       x = "Days Since First Case",
       y = "Percent Change in Weekly New Cases")
ggsave("img/ca_percent_weekly_counties.png", width = 8, height = 6, dpi = 400)
```



```{r}
ca_counties <- nyt_county_data %>% 
  filter(state == "California") %>% 
  left_join(ca_county_pops, by = "county") %>% 
  mutate(cases_per_capita = 1000 * cases / Population)
ca_counties %>% 
  group_by(county) %>% 
  mutate(days_since = date - min(date),
         core = if_else(
           county %nin% top_n_counties(ca_counties, n = 7, wt = cases_per_capita, label = county), "", county),
         linesize = if_else(core == "", 0.5, 1),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup() %>% 
  ggplot(aes(x = days_since, y = cases_per_capita, group = county, label = end_label, color = core)) +
  geom_line(aes(size = linesize)) +
  geom_text_repel(segment.color = NA, nudge_x = 2, nudge_y = 0.1) +
  theme_covid +
  labs(title = "Cases Per Capita of Coronavirus in California Counties",
       x = "Days Since First Case",
       y = "Cases Per 1,000 Population")
ggsave("img/ca_counties_per_capita.png", width = 8, height = 6, dpi = 300)
```



```{r}
ca_counties %>% 
  group_by(county) %>% 
  mutate(days_since = date - min(date),
         core = if_else(county %nin% top_n_counties(ca_counties, n = 7, wt = deaths, label = county), "", county),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ggplot(aes(x = days_since, y = deaths, group = county, label = end_label, color = core)) +
  geom_line(size = 1) +
  geom_text_repel(segment.color = NA, nudge_x = 2, nudge_y = 0.1) +
  #scale_y_log10() +
  #scale_x_continuous(limits = c(0,100)) +
  scale_color_manual(values = ghColorSelect("grey-400", "blue", "red", "green", "yellow-800", "purple", "orange", "pink")) +
  guides(color = FALSE) +
  labs(title = "Cumulative Deaths of Coronavirus in California Counties",
       x = "Days Since First Case",
       y = "Cumulative Deaths")
ggsave("img/ca_counties_deaths.png", width = 8, height = 6, dpi = 300)
```

# New York

```{r}
ny_counties <- nyt_county_data %>% 
  filter(state == "New York")
ny_counties %>% 
  group_by(county) %>% 
  mutate(days_since = date - min(date),
         core = if_else(full_name %nin% top_n_counties(ny_counties, n=7), "", county),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ggplot(aes(x = date, y = cases, group = county, label = end_label, color = core)) +
  geom_line(size = 1) +
  geom_text_repel(segment.color = NA, nudge_x = 2, nudge_y = 0.1) +
  #scale_y_log10() +
  #scale_x_continuous(limits = c(0,100)) +
  scale_color_manual(values = ghColorSelect("grey-400", "blue", "red", "green", "yellow-800", "purple", "orange", "pink")) +
  guides(color = FALSE) +
  labs(title = "Cumulative Cases of Coronavirus in NMew York Counties",
       x = "Days Since First Case",
       y = "Cumulative Cases")
```


# Illinois


```{r}
il_counties <- nyt_county_data %>% 
  filter(state == "Illinois")
il_counties %>% 
  group_by(county) %>% 
  mutate(days_since = date - min(date),
         core = if_else(full_name %nin% top_n_counties(il_counties, n=7), "", county),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup() %>% 
  left_join(il_county_pops, by = "county") %>% 
  ggplot(aes(x = days_since, y = cases_per_capita*1000, group = county, label = end_label, color = core)) +
  geom_line(size = 1) +
  geom_text_repel(segment.color = NA, nudge_x = 2, nudge_y = 0.1) +
  #scale_y_log10() +
  #scale_x_continuous(limits = c(0,100)) +
  scale_color_manual(values = ghColorSelect("grey-400", "blue", "red", "green", "yellow-800", "purple", "orange", "pink")) +
  guides(color = FALSE) +
  labs(title = "Cumulative Cases of Coronavirus in Illinois Counties",
       x = "Days Since First Case",
       y = "Cases Per 1,000")
ggsave("img/il_counties_per_capita.png", width = 8, height = 6, dpi = 300)
```



# State Level Data

```{r}
nyt_state_df %>% 
  group_by(state) %>% 
  mutate(days_since = date - min(date),
         core = if_else(state %nin% top_n_state(nyt_state_df, n=7, wt = cases_per_capita), "", state),
         linesize = if_else(core == "", 0.5, 1),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup() %>% 
  ggplot(aes(x = days_since, y = cases_per_capita, group = state, label = end_label, color = core)) +
  geom_line(size = 1) +
  geom_text_repel(segment.color = NA, nudge_x = 2, nudge_y = 0.1) +
  #scale_y_log10() +
  #scale_x_continuous(limits = c(0,100)) +
  scale_color_manual(values = ghColorSelect("grey-400", "blue", "red", "green", "yellow-800", "purple", "orange", "pink")) +
  guides(color = FALSE) +
  labs(title = "State Per Capita Cases for Top 7 States",
       x = "Days Since First Case",
       y = "Cases Per 1,000") +
  nowt()
```

```{r}
nyt_state_df %>% 
  filter(date == max(date)) %>% 
  arrange(desc(cases_per_capita)) %>% 
  select(state, cases, deaths, cases_per_capita) %>% 
  kable()
```

```{r}
nyt_state_df %>% 
  filter(date == max(date)) %>% 
  filter(fips != 11) %>% 
  ggplot(aes(x = density, y = cases_per_capita, label = state)) +
  geom_point() +
  geom_text_repel(alpha = 0.5) +
  theme_minimal() +
  theme(
    panel.grid = element_blank()
  ) +
  labs(
    title = "State Coronavirus Cases Per Capita by Pop. Density",
    y = "Cases Per 1,000 Population",
    x = "Pop. Density"
  )
ggsave("img/cases_per_capita_density.png", width = 8, height = 6, dpi = 400)
```


```{r}
state_lagged <- nyt_state_df %>% 
  mutate(lagged_date = date + days(7)) %>% 
  select(lagged_date, state, lagged_cases = cases)
state_df <- nyt_state_df %>% 
  left_join(state_lagged, by = c("state", "date" = "lagged_date")) %>% 
  mutate(
    weekly_change = cases - lagged_cases,
    change_per_capita = weekly_change / Pop,
    percent_change = (weekly_change - lag(weekly_change, 7)) / lag(weekly_change, 7),
    percent_change = if_else(percent_change == Inf, NA_real_, percent_change)
  )
gpdf <- state_df %>% 
  group_by(state) %>% 
  mutate(
    days_since = date - min(date),
    core = if_else(state %nin% top_n_state(state_df, 7, wt = change_per_capita), "", state),
    end_label = if_else(date == max(date), core, NA_character_),
    linesize = if_else(core == "", 0.5, 1)
  ) %>% 
  filter(!is.na(change_per_capita))
gpdf %>% 
  ggplot(aes(x = days_since, y = change_per_capita*1000, group = state, color = core,size = linesize, label = end_label)) +
  geom_line() +
  geom_text_repel(segment.color = NA, nudge_x = 2, size = 4) +
  theme_covid +
  labs(
    title = "New Cases in Last 7 Days Per Capita",
    x = "Days Since First Case",
    y = "New Cases Per 1,000 Pop."
  )
ggsave("img/usa_state_new_cases.png", width = 8, height = 6, dpi = 400)
```

```{r}
state_lagged <- nyt_state_df %>% 
  mutate(lagged_date = date + days(7)) %>% 
  select(lagged_date, state, lagged_cases = cases)
state_df <- nyt_state_df %>% 
  left_join(state_lagged, by = c("state", "date" = "lagged_date")) %>% 
  mutate(
    weekly_change = cases - lagged_cases,
    change_per_capita = weekly_change / Pop
  )
gpdf <- state_df %>% 
  group_by(state) %>% 
  mutate(
    days_since = date - min(date),
    core = if_else(state %nin% top_n_state(state_df, 7, wt = change_per_capita), "", state),
    end_label = if_else(date == max(date), core, NA_character_),
    linesize = if_else(core == "", 0.5, 1)
  ) %>% 
  filter(!is.na(change_per_capita))
end_date <- today() + days(10)
gpdf %>% 
  filter(date >= ymd("2020-05-01")) %>% 
  ggplot(aes(x = date, y = change_per_capita*1000, group = state, color = core,size = linesize, label = end_label)) +
  geom_line() +
  geom_text_repel(segment.color = NA, nudge_x = 2, size = 4) +
  theme_covid +
  scale_x_date(limits = c(ymd("2020-05-01"), end_date), 
               breaks = seq(ymd("2020-05-01"), today(), by = "1 week"),
               date_labels = "%b %e") +
  labs(
    title = "New Cases in Last 7 Days Per Capita",
    x = "Days Since First Case",
    y = "New Cases Per 1,000 Pop."
  )
ggsave("img/usa_state_new_cases_calendar.png", width = 8, height = 6, dpi = 400)
```



```{r}
nyt_state_df %>% 
  group_by(state) %>% 
  mutate(days_since = date - min(date),
         core = if_else(Region != "South", "", state),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup() %>% 
  filter(Region == "South") %>% 
  ggplot(aes(x = days_since, y = cases_per_capita, group = state, label = end_label, color = core)) +
  geom_line() +
  geom_text_repel(segment.color = NA, nudge_x = 2, nudge_y = 0.1) +
  #scale_y_log10() +
  #scale_x_continuous(limits = c(0,100)) +
  #scale_color_manual(values = ghColorSelect("grey-400", "blue", "red", "green", "yellow-800", "purple", "orange", "pink")) +
  guides(color = FALSE) +
  labs(title = "State Per Capita Cases for the South",
       x = "Days Since First Case",
       y = "Cases Per 1,000") +
  nowt()
ggsave("img/southern_states.png", width = 8, height = 6, dpi = 400)
```


```{r}
nyt_state_df %>% 
  #filter(cases >= 100) %>% 
  group_by(state) %>% 
  mutate(days_since = date - min(date),
         core = if_else(Region != "Midwest", "", state),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup() %>% 
  filter(Region == "Midwest") %>% 
  ggplot(aes(x = days_since, y = cases_per_capita, group = state, label = end_label, color = core)) +
  geom_line() +
  geom_text_repel(segment.color = NA, nudge_x = 2, nudge_y = 0.1) +
  #scale_y_log10() +
  #scale_x_continuous(limits = c(0,100)) +
  #scale_color_manual(values = ghColorSelect("grey-400", "blue", "red", "green", "yellow-800", "purple", "orange", "pink")) +
  guides(color = FALSE) +
  labs(title = "State Per Capita Cases for the Midwest",
       x = "Days Since First Case",
       y = "Cases Per 1,000") +
  nowt()
ggsave("img/midwest_states.png", width = 8, height = 6, dpi = 400)
```

```{r}
nyt_state_df %>% 
  group_by(state) %>% 
  mutate(days_since = date - min(date),
         core = if_else(Region != "South West", "", state),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup() %>% 
  filter(Region == "South West") %>% 
  ggplot(aes(x = days_since, y = cases_per_capita, group = state, label = end_label, color = core)) +
  geom_line() +
  geom_text_repel(segment.color = NA, nudge_x = 2, nudge_y = 0.1) +
  #scale_y_log10() +
  #scale_x_continuous(limits = c(0,100)) +
  #scale_color_manual(values = ghColorSelect("grey-400", "blue", "red", "green", "yellow-800", "purple", "orange", "pink")) +
  guides(color = FALSE) +
  labs(title = "State Per Capita Cases for the Southwest",
       x = "Days Since First Case",
       y = "Cases Per 1,000") +
  nowt()
ggsave("img/southwest_states.png", width = 8, height = 6, dpi = 400)
```



```{r}
nyt_state_df %>% 
  group_by(state) %>% 
  mutate(days_since = date - min(date),
         core = if_else(Region != "West Coast", "", state),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup() %>% 
  filter(Region == "West Coast") %>% 
  ggplot(aes(x = days_since, y = cases_per_capita, group = state, label = end_label, color = core)) +
  geom_line() +
  geom_text_repel(segment.color = NA, nudge_x = 2, nudge_y = 0.1) +
  #scale_y_log10() +
  #scale_x_continuous(limits = c(0,100)) +
  #scale_color_manual(values = ghColorSelect("grey-400", "blue", "red", "green", "yellow-800", "purple", "orange", "pink")) +
  guides(color = FALSE) +
  labs(title = "State Per Capita Cases for the West Coast",
       x = "Days Since First Case",
       y = "Cases Per 1,000") +
  nowt()
ggsave("img/west_states.png", width = 8, height = 6, dpi = 400)
```

# Counties

```{r}
county_df <- nyt_county_data %>% 
  filter(population < 500000) %>% 
  group_by(county) %>% 
  arrange(date) %>% 
  mutate(percent_weekly_change = (cases - lag(cases)) / lag(cases),
         percent_weekly_change = case_when(
           cases < 100 ~ NA_real_,
           percent_weekly_change == Inf ~ NA_real_,
           date == max(date) ~ percent_weekly_change,
           TRUE ~ NA_real_
         )) %>% 
  ungroup()
gpdf <- county_df %>% 
  filter(full_name %in% top_n_counties(county_df, n = 20, wt = cases_per_capita))
gpdf <- gpdf %>% 
  group_by(county) %>% 
  mutate(days_since = date - min(date),
         core = if_else(
           full_name %nin% top_n_counties(gpdf, n=7, wt = cases_per_capita), "", 
           full_name 
           ),
         linesize = if_else(core == "", 0.5, 1),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup()


gpdf %>% 
    ggplot(aes(x = days_since, y = cases_per_capita*1000, group = full_name, label = end_label, color = core)) +
  geom_line(aes(size = linesize)) +
  geom_text_repel(segment.color = NA, nudge_x = 2) +
  #scale_y_log10() +
  #scale_x_continuous(limits = c(0,100)) +
  scale_color_manual(values = ghColorSelect("grey-400", "blue", "red", "green", "yellow-800", "purple", "orange", "pink")) +
  scale_size_identity() +
  guides(color = FALSE) +
  labs(title = "Cases Per Capita of Coronavirus in Rural Counties",
       caption = "Counties with less than 500,000 population",
       x = "Days Since First Case",
       y = "Cases Per 1,000 Population")
ggsave("img/rural_counties.png", width = 8, height = 6, dpi = 400)
```



```{r}
gpdf <- county_df %>% 
  filter(full_name %in% top_n_counties(county_df, n = 20, wt = cases))
gpdf <- gpdf %>% 
  group_by(county) %>% 
  mutate(days_since = date - min(date),
         core = if_else(
           full_name %nin% top_n_counties(gpdf, n=7, wt = cases), "", 
           full_name 
           ),
         linesize = if_else(core == "", 0.5, 1),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup()


gpdf %>% 
    ggplot(aes(x = days_since, y = cases, group = full_name, label = end_label, color = core)) +
  geom_line(aes(size = linesize)) +
  geom_text_repel(segment.color = NA, nudge_x = 2) +
  #scale_y_log10() +
  #scale_x_continuous(limits = c(0,100)) +
  scale_color_manual(values = ghColorSelect("grey-400", "blue", "red", "green", "yellow-800", "purple", "orange", "pink")) +
  scale_size_identity() +
  guides(color = FALSE) +
  labs(title = "Cumulative Cases of Coronavirus in Rural Counties",
       caption = "Counties with less than 100,000 population",
       x = "Days Since First Case",
       y = "Cases")
ggsave("img/rural_counties_raw.png", width = 8, height = 6, dpi = 400)
```

```{r}
lagged_data <- nyt_county_data %>% 
  mutate(lag7 = date + days(7)) %>% 
  select(full_name, lag7, cases_lagged7 = cases)

county_df <- nyt_county_data %>% 
  filter(!is.na(population)) %>% 
  left_join(lagged_data, by = c("full_name" = "full_name", "date" = "lag7")) %>% 
  mutate(weekly_change = cases - cases_lagged7,
         change_per_capita = weekly_change / population
         )
gpdf <- county_df %>% 
  filter(full_name %in% top_n_counties(county_df, n = 20, wt = change_per_capita))
gpdf <- gpdf %>% 
  group_by(full_name) %>% 
  mutate(days_since = date - min(date),
         core = if_else(
           full_name %nin% top_n_counties(gpdf, n=7, wt = change_per_capita, label = full_name), "", 
           full_name 
           ),
         linesize = if_else(core == "", 0.5, 1),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup() %>% 
  filter(!is.na(weekly_change))

gpdf %>% 
  #filter(date >= ymd("2020-04-01")) %>% 
    ggplot(aes(x = days_since, y = change_per_capita*1000, group = full_name, label = end_label, color = core)) +
  geom_line(aes(size = linesize)) +
  geom_text_repel(segment.color = NA, nudge_x = 2) +
  theme(
    panel.background = element_blank(),
    panel.grid.major.y = element_line(color = ghColorSelect("grey-200"))
  ) +
  #scale_y_log10() +
  #scale_x_continuous(limits = c(0,100)) +
  scale_color_manual(values = ghColorSelect("grey-400", "blue", "red", "green", "yellow-800", "purple", "orange", "pink")) +
  scale_size_identity() +
  guides(color = FALSE) +
  labs(title = "New Cases In Last 7 Days Per Capita, U.S. Counties",
       x = "Days Since First Case",
       y = "New Cases in Last 7 Days Per 1,000 Pop.")
ggsave("img/usa_weekly_counties.png", width = 8, height = 6, dpi = 400)
```

```{r}
county_df %>% 
  filter(county == "Lake" & state == "Tennessee") %>% 
  arrange(desc(date))
```


```{r}
start_date <- floor_date(today() - months(1), unit = "month")
end_date <- today() + days(10)
gpdf %>% 
  filter(date >= start_date) %>% 
  ggplot(aes(x = date, y = change_per_capita*1000, group = full_name, label = end_label, color = core)) +
  geom_line(aes(size = linesize)) +
  geom_text_repel(segment.color = NA, nudge_x = 2) +
  theme(
    panel.background = element_blank(),
    panel.grid.major.y = element_line(color = ghColorSelect("grey-200"))
  ) +
  scale_x_date(limits = c(start_date, end_date),
               breaks = seq(start_date, today(), "1 week"),
               date_labels = "%b %e") +
  #scale_y_log10() +
  #scale_x_continuous(limits = c(0,100)) +
  scale_color_manual(values = ghColorSelect("grey-400", "blue", "red", "green", "yellow-800", "purple", "orange", "pink")) +
  scale_size_identity() +
  guides(color = FALSE) +
  labs(title = "New Cases In Last 7 Days Per Capita, U.S. Counties",
       x = "Days Since First Case",
       y = "New Cases in Last 7 Days Per 1,000 Pop.")
ggsave("img/usa_weekly_counties_calendar.png", width = 8, height = 6, dpi = 400)
```


```{r}
lagged_data <- nyt_county_data %>% 
  mutate(lag7 = date + days(7)) %>% 
  select(full_name, lag7, deaths_lagged7 = deaths)

county_df <- nyt_county_data %>% 
  filter(!is.na(population)) %>% 
  left_join(lagged_data, by = c("full_name" = "full_name", "date" = "lag7")) %>% 
  mutate(weekly_change = deaths - deaths_lagged7,
         change_per_capita = weekly_change / population
         )
gpdf <- county_df %>% 
  filter(full_name %in% top_n_counties(county_df, n = 20, wt = change_per_capita))
gpdf <- gpdf %>% 
  group_by(full_name) %>% 
  mutate(days_since = date - min(date),
         core = if_else(
           full_name %nin% top_n_counties(gpdf, n=7, wt = change_per_capita, label = full_name), "", 
           full_name 
           ),
         linesize = if_else(core == "", 0.5, 1),
         end_label = if_else(date == max(date), core, NA_character_)) %>% 
  ungroup() %>% 
  filter(!is.na(weekly_change))

gpdf %>% 
  #filter(date >= ymd("2020-04-01")) %>% 
    ggplot(aes(x = days_since, y = change_per_capita*1000, group = full_name, label = end_label, color = core)) +
  geom_line(aes(size = linesize)) +
  geom_text_repel(segment.color = NA, nudge_x = 2) +
  theme(
    panel.background = element_blank(),
    panel.grid.major.y = element_line(color = ghColorSelect("grey-200"))
  ) +
  #scale_y_log10() +
  #scale_x_continuous(limits = c(0,100)) +
  scale_color_manual(values = ghColorSelect("grey-400", "blue", "red", "green", "yellow-800", "purple", "orange", "pink")) +
  scale_size_identity() +
  guides(color = FALSE) +
  labs(title = "New Deaths In Last 7 Days Per Capita, U.S. Counties",
       x = "Days Since First Case",
       y = "Deaths Per 1,000 Pop.")
ggsave("img/usa_weekly_deaths_counties.png", width = 8, height = 6, dpi = 400)
```